name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  sonar-backend:
    permissions:
      pull-requests: read  # allows SonarCloud to decorate PRs with analysis results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Analyze with SonarCloud
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=sosaidi -Dsonar.projectKey=sosaidi_AdvancedMD-backend -Dsonar.login=1bbe0b2d39c5e66f4b2999aae153e491792710d7 -Dsonar.exclusions=\*\*/\*.java -Dsonar.projectName=sosaidi/AdvancedMD-backend


  jacoco:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up the Java JDK
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badges for Authentication service
        id: jacocoMod1
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true
          jacoco-csv-file: authentication-service/target/site/jacoco/jacoco.csv

      - name: Generate JaCoCo Badges for Doctor-service
        id: jacocoMod2
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true
          jacoco-csv-file: doctor-service/target/site/jacoco/jacoco.csv

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
            coverage_results_path: authentication-service/target/site/jacoco/jacoco.xml
            coverage_report_name: Authentication- Service Coverage
            coverage_report_title: JaCoCo
            github_token: ${{ secrets.GITHUB_TOKEN }}
            skip_check_run: false
            minimum_coverage: 10
            fail_below_threshold: false
            publish_only_summary: false

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
                default_author: github_actions
                message: 'commit badge'
                add: '*.svg'

     
