name: CI
on:
  push:
    branches:

  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:

      - name: SonarCloud Scan
        run: mvn clean verify sonar:sonar
          -Dsonar.projectKey=sosaidi_AdvancedMD-backend \
          -Dsonar.organization=sosaidi \
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'   # Specify the version of Java you are using
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      

      - name: Build with Maven
        run: mvn clean install


      - name: Run Unit Tests
        run: mvn test

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

    

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}