name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  sonar-backend:
    permissions:
      pull-requests: read  # allows SonarCloud to decorate PRs with analysis results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Analyze with SonarCloud
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=sosaidi -Dsonar.projectKey=sosaidi_AdvancedMD-backend -Dsonar.login=1bbe0b2d39c5e66f4b2999aae153e491792710d7 -Dsonar.exclusions=\*\*/\*.java -Dsonar.projectName=sosaidi/AdvancedMD-backend


  jacoco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up the Java JDK
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
                generate-branches-badge: true
                jacoco-csv-file: >
                  authentication-service/target/site/jacoco/jacoco.csv
                  doctor-service/target/site/jacoco/jacoco.csv

      - name: Log coverage percentage
        run: |
                echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
                echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
                if [[ `git status --porcelain` ]]; then
                  git config --global user.name 'Annabelle'
                  git config --global user.email 'YOUR-GITHUB-USERID@annclermont@edu.aau.at'
                  git add -A
                  git commit -m "Autogenerated JaCoCo coverage badge"
                  git push
                fi

     
