name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  sonar-backend:
    permissions:
      pull-requests: read  # allows SonarCloud to decorate PRs with analysis results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Analyze with SonarCloud
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=sosaidi \
          -Dsonar.projectKey=sosaidi_AdvancedMD-backend \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.exclusions=**/*.java \
          -Dsonar.projectName=sosaidi/AdvancedMD-backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 10
          min-coverage-changed-files: 40

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-with-reusable-workflow:
    uses: spring-guides/getting-started-macros/.github/workflows/build_initial_complete_maven_gradle.yml@main
